# Setup
title: Belce Kaya
description: >
  Data Scientist / Data Engineer/ Industrial Engineer
  
url: https://belcekaya.github.io
avatar: /images/Picture1.jpg 
paginate: 5
permalink: pretty
cover_image: /images/background2.jpg

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts/

linkedin:
  username: belcekaya
  card: summary
logo: logo.png
social:
  name: Belce Kaya
  links:
    - https://www.linkedin.com/in/belcekaya/
    - https://github.com/belcekaya
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Enabling disqus
# disqus: xxxxxx
